// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-X0TGTVadVA5SOXMJP5CR8qRjaXcf2S4',
    appId: '1:1056086192112:web:c6f3c79c0a5f71d3c0b735',
    messagingSenderId: '1056086192112',
    projectId: 'chat-app-88600',
    authDomain: 'chat-app-88600.firebaseapp.com',
    storageBucket: 'chat-app-88600.appspot.com',
    measurementId: 'G-DFKJG7ZE7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlmTpW0u2B5Vlt1nR2E25ELp3-Frd7R8g',
    appId: '1:1056086192112:android:065db097e73859d7c0b735',
    messagingSenderId: '1056086192112',
    projectId: 'chat-app-88600',
    storageBucket: 'chat-app-88600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIgSJe3h3wHuEayhVivJYI3y1to8ox2Cg',
    appId: '1:1056086192112:ios:e7d47c2b51ff156bc0b735',
    messagingSenderId: '1056086192112',
    projectId: 'chat-app-88600',
    storageBucket: 'chat-app-88600.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIgSJe3h3wHuEayhVivJYI3y1to8ox2Cg',
    appId: '1:1056086192112:ios:e7d47c2b51ff156bc0b735',
    messagingSenderId: '1056086192112',
    projectId: 'chat-app-88600',
    storageBucket: 'chat-app-88600.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-X0TGTVadVA5SOXMJP5CR8qRjaXcf2S4',
    appId: '1:1056086192112:web:0d4f2f3e795481fcc0b735',
    messagingSenderId: '1056086192112',
    projectId: 'chat-app-88600',
    authDomain: 'chat-app-88600.firebaseapp.com',
    storageBucket: 'chat-app-88600.appspot.com',
    measurementId: 'G-RN2V0G1G61',
  );
}
